# Generated by Django 5.0.7 on 2024-07-30 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front', models.CharField(max_length=255, unique=True)),
                ('back', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UsageExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front', models.CharField(max_length=1024)),
                ('back', models.CharField(default='Empty', max_length=1024)),
                ('word_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word_cards.wordcard')),
            ],
        ),
    ]
